package com.inpranet.habit.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Sun Mar 20 23:15:35 CET 2011
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "http://service.habit.inpranet.com/", name = "IHabitService")
@XmlSeeAlso({ObjectFactory.class})
public interface IHabitService {

    @RequestWrapper(localName = "StockData", targetNamespace = "http://service.habit.inpranet.com/", className = "com.inpranet.habit.service.StockData")
    @WebMethod(operationName = "StockData")
    @ResponseWrapper(localName = "StockDataResponse", targetNamespace = "http://service.habit.inpranet.com/", className = "com.inpranet.habit.service.StockDataResponse")
    public void stockData(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "coordinate", targetNamespace = "")
        com.inpranet.habit.service.Coordinate coordinate
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "DeduceZone", targetNamespace = "http://service.habit.inpranet.com/", className = "com.inpranet.habit.service.DeduceZone")
    @WebMethod(operationName = "DeduceZone")
    @ResponseWrapper(localName = "DeduceZoneResponse", targetNamespace = "http://service.habit.inpranet.com/", className = "com.inpranet.habit.service.DeduceZoneResponse")
    public java.lang.String deduceZone(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "planningHorizon", targetNamespace = "")
        int planningHorizon,
        @WebParam(name = "interest", targetNamespace = "")
        int interest
    );
}
