package com.inpranet.core.ws.bus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Sun Mar 27 17:07:19 CEST 2011
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "http://service.frontservice.inpranet.com/", name = "IInternalService")
@XmlSeeAlso({ObjectFactory.class})
public interface IInternalService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getZoneListFromGeoPos", targetNamespace = "http://service.frontservice.inpranet.com/", className = "com.inpranet.core.ws.bus.GetZoneListFromGeoPos")
    @WebMethod
    @ResponseWrapper(localName = "getZoneListFromGeoPosResponse", targetNamespace = "http://service.frontservice.inpranet.com/", className = "com.inpranet.core.ws.bus.GetZoneListFromGeoPosResponse")
    public java.util.List<com.inpranet.core.ws.bus.Zone> getZoneListFromGeoPos(
        @WebParam(name = "geopos", targetNamespace = "")
        com.inpranet.core.ws.bus.GeoPos geopos
    );
}
