
/*
 * 
 */

package com.inpranet.core.ws.bus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.7
 * Sun Mar 27 14:06:14 CEST 2011
 * Generated source version: 2.2.7
 * 
 */


@WebServiceClient(name = "InternalServiceService", 
                  wsdlLocation = "file:/home/yoann/workspace/inpranet4/core/src/main/resources/bus.wsdl",
                  targetNamespace = "http://service.frontservice.inpranet.com/") 
public class InternalServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.frontservice.inpranet.com/", "InternalServiceService");
    public final static QName InternalServicePort = new QName("http://service.frontservice.inpranet.com/", "InternalServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/yoann/workspace/inpranet4/core/src/main/resources/bus.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/yoann/workspace/inpranet4/core/src/main/resources/bus.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public InternalServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InternalServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InternalServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IInternalService
     */
    @WebEndpoint(name = "InternalServicePort")
    public IInternalService getInternalServicePort() {
        return super.getPort(InternalServicePort, IInternalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IInternalService
     */
    @WebEndpoint(name = "InternalServicePort")
    public IInternalService getInternalServicePort(WebServiceFeature... features) {
        return super.getPort(InternalServicePort, IInternalService.class, features);
    }

}
