
/*
 * 
 */

package com.inpranet.habit.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.7
 * Sun Mar 20 23:15:35 CET 2011
 * Generated source version: 2.2.7
 * 
 */


@WebServiceClient(name = "HabitServiceImpService", 
                  wsdlLocation = "file:/C:/Documents%20and%20Settings/sopra/Bureau/inpranet_trunk/Service/src/main/resources/wsdl/habit.wsdl",
                  targetNamespace = "http://service.habit.inpranet.com/") 
public class HabitServiceImpService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.habit.inpranet.com/", "HabitServiceImpService");
    public final static QName HabitServiceImpPort = new QName("http://service.habit.inpranet.com/", "HabitServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Documents%20and%20Settings/sopra/Bureau/inpranet_trunk/Service/src/main/resources/wsdl/habit.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/Documents%20and%20Settings/sopra/Bureau/inpranet_trunk/Service/src/main/resources/wsdl/habit.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public HabitServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HabitServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HabitServiceImpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IHabitService
     */
    @WebEndpoint(name = "HabitServiceImpPort")
    public IHabitService getHabitServiceImpPort() {
        return super.getPort(HabitServiceImpPort, IHabitService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHabitService
     */
    @WebEndpoint(name = "HabitServiceImpPort")
    public IHabitService getHabitServiceImpPort(WebServiceFeature... features) {
        return super.getPort(HabitServiceImpPort, IHabitService.class, features);
    }

}
